spring:
  datasource:
    url: jdbc:postgresql://localhost:55000/hiring
    username: postgres
    password: postgrespw
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yml
    liquibase-schema: liquibase
    default-schema: tracker

  application:
    name: hiring
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

jwt.secret: secret
server:
  port: 8083