spring:
  application:
    name: eureka-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8761

eureka:
  instance:
    hostname: eureka
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false