spring:
  datasource:
    url: jdbc:postgresql://localhost:55000/teamsync
    username: postgres
    password: postgrespw
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yml
    liquibase-schema: liquibase
    default-schema: tracker
  jackson:
    serialization:
      fail-on-empty-beans: false
  kafka:
    bootstrap-servers: localhost:29092
  #  jackson:
#    property-naming-strategy: SNAKE_CASE

  application:
    name: tracker
  cloud:
    loadbalancer:
      ribbon:
        enabled: false


jwt.secret: secret
server:
  port: 8081
