name: compile all services

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: set up java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: eureka
        run: mvn -B clean package -f backend/eureka/
      - name: gateway
        run: mvn -B clean package -f backend/gateway/
      - name: auth
        run: mvn -B clean package -f backend/authentication/
      - name: backend
        run: mvn -B clean package -f backend/backend/
      - name: hiring
        run: mvn -B clean package -f backend/hiring/
